# Site
repository: simonezz.github.io
# favicon: Directory of your favicon (eg. images/favicon.ico)(optional)

# Content configuration version
version: 2

# Personal info
name: Saehee Jeon
title: 꾸준히 공부하는 개발자
email: saeheejeon25@gmail.com
# email_title: Email (Email title override)

# phone_title: Phone (Phone title override)
website: simonezz.tistory.com
# website_title: Web (Website title override)

# Dark Mode (true/false/never)
darkmode: never

# Social links

github_username:  simonezz
linkedin_username: saehee-jeon-752482188

# Additional icon links
additional_links:
- title: Link name
  icon: Font Awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&s=brands&m=free)
  url: Link url (eg. https://google.com)
# - title: another link
#   icon: font awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&s=brands&m=free)
#   url: Link url (eg. https://google.com)

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"

# About Section
# about_title: About Me (Use this to override about section title)
about_profile_image: images/profile.jpg
about_content: | # this will include new lines to allow paragraphs
  어렸을 때부터 수학을 좋아하여 수학과에 진학 후 프로그래밍에 관심이 생겨 부전공 이후 개발의 재미에 빠져 꾸준히 공부하고 있는 전세희입니다.
  석사로 이미지 프로세싱 분야를 전공 후 이미지, 자연어 도메인에 관심을 가지고 꾸준히 공부하고 있습니다.
  현재 한 스타트업에서 추천시스템 연구/개발 직무를 맡고 있습니다. 콘텐츠의 유사성을 텍스트/이미지 기반으로 측정하는 방법을 개발한 후 이를 고도화 하는 과정에 있습니다.
  유저의 활동로그를 기반으로 추천하는 방법 또한 기획중입니다.
  
  관심 분야
  - Recommendation system, ranking, information retrieval
  - Computer Vision : segmentation, detection, classification, OCR
  - NLP : sentence embeddings, word embeddings, translation
  - Data Engineering
  - Graph Neural Network

content:
  - title: Projects # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: Recommender System
        link: https://github.com/simonezz/RecSys
        link_text: Github
        description: | # this will include new lines to allow paragraphs
          - Python, Elasticsearch, MySQL
          - 이미지와 텍스트 관점에서 데이터간의 유사도 계산
          
          
  - title: Experience
    layout: list
    content:
      - layout: right
        title: Freewheelin
        sub_title: 추천시스템 연구/개발
        caption: July 2020 - present
        description: | # this will include new lines to allow paragraphs
          학생들의 성적 향상을 위한 추천시스템 개발(유사문제 검색, 학생 맞춤 서비스 개발)
        quote: >
          수학문제 은행 소프트웨어 스타트업
          
  - title: Education
    layout: list
    content:
      - layout: top-left
        title: Ewha w.univ
        sub_title: BA Mathematics
        caption: 2014.03 -2018.02
        description: |
           - 수학 전공 / 계산과학 부전공
           - GPA 3.96/4.5
           - S.E.M(Sweet Ewha Math) 동아리 활동(2015/03~2017/12)
           - 수학과 편집부 활동(2016/04~2018/02)
           - 이화 모교 방문단 활동(2014/05)

        
      - layout: top-right
        title: Ewha w.univ
        sub_title: MS Mathematics
        caption: 2018.03-2020.02
        description: | # this will include new lines to allow paragraphs
          - Image processing을 세부전공으로 Image Denoising, Approximation Theory,
          - Numerical Analysis, Deep Learning 분야 학습/연구.
          - GPA 4.8/4.5
         
          
  - title: Interest
    layout: text
    content: | # this will include new lines to allow paragraphs
      - tech : 추천시스템, 데이터 사이언스, 컴퓨터비전, 자연어처리, aws, 데이터 엔지니어링
      - workout : 자전거, 클라이밍, 요가
      - else : 불어, 영어회화, 독서(특히 정세랑 작가님 책들), 인공지능 윤리, 피아노

  - title: Skills
    layout: text
    content: | # this will include new lines to allow paragraphs
      Python, Matlab, C, SQL, Elasticsearch, English

# Footer
footer_show_references: true
# references_title: References on request (Override references text)

# Build settings
# theme: modern-resume-theme (Use this is you are hosting your resume yourself)
# remote_theme: sproogen/modern-resume-theme (Use this if you are hosting your resume on GitHub)

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag

exclude : [
  "Gemfile",
  "Gemfile.lock",
  "node_modules",
  "vendor/bundle/",
  "vendor/cache/",
  "vendor/gems/",
  "vendor/ruby/",
  "lib/",
  "scripts/",
  "docker-compose.yml",
  ]
